
package employee.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeSoap", targetNamespace = "http://webservice.employee/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeSoap {


    /**
     * 
     * @param employeeId
     * @return
     *     returns employee.webservice.Employee
     */
    @WebMethod
    @WebResult(name = "Employee", partName = "Employee")
    @Action(input = "http://webservice.employee/EmployeeSoap/getEmployeeRequest", output = "http://webservice.employee/EmployeeSoap/getEmployeeResponse")
    public Employee getEmployee(
        @WebParam(name = "employee_id", partName = "employee_id")
        long employeeId);

    /**
     * 
     * @param employee
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice.employee/EmployeeSoap/createEmployeeRequest", output = "http://webservice.employee/EmployeeSoap/createEmployeeResponse")
    public String createEmployee(
        @WebParam(name = "Employee", partName = "Employee")
        Employee employee);

    /**
     * 
     * @return
     *     returns employee.webservice.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "GroupOfEmployee", partName = "GroupOfEmployee")
    @Action(input = "http://webservice.employee/EmployeeSoap/readEmployeeRequest", output = "http://webservice.employee/EmployeeSoap/readEmployeeResponse")
    public GroupOfEmployee readEmployee();

    /**
     * 
     * @param pincode
     * @return
     *     returns employee.webservice.GroupOfEmployee
     */
    @WebMethod
    @WebResult(name = "GroupOfEmployee", partName = "GroupOfEmployee")
    @Action(input = "http://webservice.employee/EmployeeSoap/readEmployeeByPincodeRequest", output = "http://webservice.employee/EmployeeSoap/readEmployeeByPincodeResponse")
    public GroupOfEmployee readEmployeeByPincode(
        @WebParam(name = "pincode", partName = "pincode")
        int pincode);

}
