//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.28 at 07:49:56 AM IST 
//


package service.transaction;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the service.transaction package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: service.transaction
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindBySenderRequest }
     * 
     */
    public FindBySenderRequest createFindBySenderRequest() {
        return new FindBySenderRequest();
    }

    /**
     * Create an instance of {@link UpdateRemarksResponse }
     * 
     */
    public UpdateRemarksResponse createUpdateRemarksResponse() {
        return new UpdateRemarksResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link AddTransactionResponse }
     * 
     */
    public AddTransactionResponse createAddTransactionResponse() {
        return new AddTransactionResponse();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link FindByReceiverRequest }
     * 
     */
    public FindByReceiverRequest createFindByReceiverRequest() {
        return new FindByReceiverRequest();
    }

    /**
     * Create an instance of {@link RemoveTransactionByDatesRequest }
     * 
     */
    public RemoveTransactionByDatesRequest createRemoveTransactionByDatesRequest() {
        return new RemoveTransactionByDatesRequest();
    }

    /**
     * Create an instance of {@link RemoveTransactionByDatesResponse }
     * 
     */
    public RemoveTransactionByDatesResponse createRemoveTransactionByDatesResponse() {
        return new RemoveTransactionByDatesResponse();
    }

    /**
     * Create an instance of {@link FindBySenderResponse }
     * 
     */
    public FindBySenderResponse createFindBySenderResponse() {
        return new FindBySenderResponse();
    }

    /**
     * Create an instance of {@link FindByAmountRequest }
     * 
     */
    public FindByAmountRequest createFindByAmountRequest() {
        return new FindByAmountRequest();
    }

    /**
     * Create an instance of {@link AddTransactionRequest }
     * 
     */
    public AddTransactionRequest createAddTransactionRequest() {
        return new AddTransactionRequest();
    }

    /**
     * Create an instance of {@link FindByAmountResponse }
     * 
     */
    public FindByAmountResponse createFindByAmountResponse() {
        return new FindByAmountResponse();
    }

    /**
     * Create an instance of {@link UpdateRemarksRequest }
     * 
     */
    public UpdateRemarksRequest createUpdateRemarksRequest() {
        return new UpdateRemarksRequest();
    }

    /**
     * Create an instance of {@link FindByReceiverResponse }
     * 
     */
    public FindByReceiverResponse createFindByReceiverResponse() {
        return new FindByReceiverResponse();
    }

}
