
package mybank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionsService", targetNamespace = "http://mybank/", wsdlLocation = "http://localhost:1010/mybank?wsdl")
public class TransactionsService
    extends Service
{

    private final static URL TRANSACTIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONSSERVICE_EXCEPTION;
    private final static QName TRANSACTIONSSERVICE_QNAME = new QName("http://mybank/", "TransactionsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1010/mybank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONSSERVICE_WSDL_LOCATION = url;
        TRANSACTIONSSERVICE_EXCEPTION = e;
    }

    public TransactionsService() {
        super(__getWsdlLocation(), TRANSACTIONSSERVICE_QNAME);
    }

    public TransactionsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONSSERVICE_QNAME, features);
    }

    public TransactionsService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONSSERVICE_QNAME);
    }

    public TransactionsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONSSERVICE_QNAME, features);
    }

    public TransactionsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Transactions
     */
    @WebEndpoint(name = "TransactionsPort")
    public Transactions getTransactionsPort() {
        return super.getPort(new QName("http://mybank/", "TransactionsPort"), Transactions.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Transactions
     */
    @WebEndpoint(name = "TransactionsPort")
    public Transactions getTransactionsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mybank/", "TransactionsPort"), Transactions.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONSSERVICE_EXCEPTION!= null) {
            throw TRANSACTIONSSERVICE_EXCEPTION;
        }
        return TRANSACTIONSSERVICE_WSDL_LOCATION;
    }

}
